services:
  - type: web
    name: sitec-wordpress
    runtime: docker
    plan: starter
    envVars:
      - key: DB_NAME
        fromService:
          type: pserv
          name: sitec-mysql
          property: databaseName
      - key: DB_USER
        fromService:
          type: pserv
          name: sitec-mysql
          property: user
      - key: DB_PASSWORD
        fromService:
          type: pserv
          name: sitec-mysql
          property: password
      - key: DB_HOST
        fromService:
          type: pserv
          name: sitec-mysql
          property: host
      - key: WP_HOME
        value: https://sitec-wordpress.onrender.com
      - key: WP_SITEURL
        value: https://sitec-wordpress.onrender.com
      - key: DISABLE_WP_CRON
        value: "1"
      - key: FORCE_SSL_ADMIN
        value: "1"

  - type: pserv
    name: sitec-mysql
    env: docker
    plan: starter
    dockerCommand: >-
      bash -lc "docker-entrypoint.sh mysqld --default-authentication-plugin=mysql_native_password"
    repo: https://github.com/render-examples/mysql
    branch: main
    envVars:
      - key: MYSQL_DATABASE
        generateValue: true
      - key: MYSQL_USER
        generateValue: true
      - key: MYSQL_PASSWORD
        generateValue: true
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 10
